name: HW Release

on:
  # Workflow runs when a main branch PR is created
  #pull_request:
  #  branches: [ main ]

  # Workflow can also be run manually
  workflow_dispatch:

jobs:
  variables:
    name: Build Variables
    runs-on: ubuntu-22.04
    outputs:
      date_str: ${{ steps.date.outputs.date }}

    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

  update-rtl:
    name: Update RTL Submodule
    runs-on: ubuntu-22.04
    needs: variables
    outputs:
      branch_name: ${{ steps.branch.outputs.branch }}
      ci_checks_needed: ${{ steps.status.outputs.status }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Update the Caliptra RTL submodule and rebuild registers
        run: |
          git submodule update --remote hw-latest/caliptra-rtl
          cargo run --release --manifest-path registers/bin/generator/Cargo.toml -- hw-latest/caliptra-rtl registers/src/

      - name: Prevent repo building...
        run: |
          rm -rf Cargo.toml Cargo.lock

      - name: Find available branch name
        id: branch
        run: |
          BRANCH_BASE=ci_run_${{ needs.variables.outputs.date_str }}
          INDEX=0
          while git ls-remote --exit-code --heads origin ${BRANCH_BASE}_${INDEX}
          do
              echo Nope
              ((INDEX+=1))
          done
          echo "branch=${BRANCH_BASE}_${INDEX}" >> $GITHUB_OUTPUT

      - name: Run git status
        id: status
        run: echo "status=$(git status -s | head -1)" >> $GITHUB_OUTPUT

      # If there's a new HW release (submodule has been updated), add a commit to main branch
      - name: Commit changes
        if: ${{ steps.status.outputs.status }}
        run: |
          git config --global user.name "GitHub CI"
          git config --global user.email "username@users.noreply.github.com"
          git checkout -b ci_failure_${{ needs.variables.outputs.date_str }}
          git commit -a -m "CI: Update Caliptra RTL"
          git push -f -u origin ci_failure_${{ needs.variables.outputs.date_str }}

  #build-test:
  #  uses: amd-isaac/caliptra-sw/.github/workflows/build-test.yml@isaac_nightly_release
  #  needs: update-rtl
  #  if: needs.update-rtl.outputs.ci_checks_needed

  build-test-verilator:
    uses: amd-isaac/caliptra-sw/.github/workflows/build-test-verilator.yml@isaac_nightly_release
    needs: [variables, update-rtl]
    if: needs.update-rtl.outputs.ci_checks_needed
    with:
      ref: ci_failure_${{ needs.variables.outputs.date_str }}

  hw-release-test:
    name: HW Release Test
    runs-on: ubuntu-22.04
    timeout-minutes: 360

    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      # If there's a new commit, push it now so we don't have to rerun the above tests again

      # Find the last successful release tag in the repo

      # Make sure there are commits between current and last successful release

      #- name: Run Verilator full tests
      #  uses: amd-isaac/caliptra-sw/.github/workflows/nightly-verilator.yml@isaac_nightly_release

      # FIXME: Use the correct release generation process here
      #- name: Generate release zip
      #  run: |
      #    mkdir /tmp/hw_release_${{ steps.date.outputs.date}}
      #    cp target/riscv32imc-unknown-none-elf/firmware/caliptra-rom /tmp/hw_release_${{ steps.date.outputs.date}}

      # FIXME: Tag with the correct "next release number"
      #- name: Upload release
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: release
      #    path: /tmp/hw_release_${{ steps.date.outputs.date }}/caliptra-rom

      # Add "next release number" to the repo as a tag, then push it

