name: HW Release (for now manually triggered)
on:
  pull_request:
  workflow_dispatch:

jobs:
  smoke_test:
    name: HW Release Test
    runs-on: ubuntu-22.04
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v3

      - name: Get current date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        id: date

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Update Submodules
        run: |
          git submodule update --init

      - name: Update the RTL Repo Pointer
        run: |
          git submodule update --remote hw-latest/caliptra-rtl
          cargo run --release --manifest-path registers/bin/generator/Cargo.toml -- hw-latest/caliptra-rtl registers/src/

      - name: Run git status
        id: status
        run: echo "::set-output name=status::$(git status -s)"

      - name: GIT commit and create pull request
        env:
          CI_COMMIT_MESSAGE: Continuous Integration Update Caliptra RTL
          CI_COMMIT_AUTHOR: Continuous Integration
        if: ${{ steps.status.outputs.status }}
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"

      - name: Create Pull Request
        if: ${{ steps.status.outputs.status }}
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}

      - name: Trigger Nightly Workflow
        run: |
          echo "Need to trigger nightly workflow"

      - name: Generate release zip
        run: |
          mkdir /tmp/hw_release_${{ steps.date.outputs.date}}
          cp target/riscv32imc-unknown-none-elf/firmware/caliptra-rom /tmp/hw_release_${{ steps.date.outputs.date}}

      - name: Upload release
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: /tmp/hw_release_${{ steps.date.outputs.date }}/caliptra-rom

